name: CI/CD Workflow for the Assessment Project

on:
  push:
    branches:
      - main  # Trigger only on push to main

jobs:
  init_test_and_deploy:
    name: Init, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.12.1
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Perform Static Analysis with ESLint
      run: npx eslint -o eslint_report.json -f json
      continue-on-error: true

    - name: Create ESLint Annotations
      uses: ataylorme/eslint-annotate-action@v3
      with:
        only-pr-files: false

    - name: Run Unit Tests with Jest
      run: npm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Push Test Image
    - name: Build Docker Image (Test Image)
      run: |
        docker build -f Dockerfiles/test.Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/earnest-thomas-intro-to-devops-a2:test-latest .

    - name: Push Test Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/earnest-thomas-intro-to-devops-a2:test-latest

    # Build and Push User-Facing Image
    - name: Build Docker Image (User Image)
      run: |
        docker build -f Dockerfiles/user.Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/earnest-thomas-intro-to-devops-a2:latest .

    - name: Push User Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/earnest-thomas-intro-to-devops-a2:latest
